local:
  shared: standard_shared_local
  clusters: standard_clusters_local

local_and_capella:
  shared: standard_shared_local_and_capella
  clusters: standard_clusters_local_and_capella

local_and_capella_aws_eu_central:
  shared: standard_shared_local_and_capella
  clusters: standard_clusters_local_and_capella_aws_eu_central

shared_local:
  metadata: standard_metadata
  data_structures: standard_data_structures
  services: standard_services

shared_local_and_capella:
  metadata: standard_metadata
  data_structures: standard_data_structures
  capella_projects: standard_capella_projects
  services: standard_services

metadata:
  bucket: main
  scope: cillers_metadata

data_structures:
  main:
    type: cluster

capella_projects:
  production: 
    organization_id: !env CAPELLA_MAIN_ORGANIZATION_ID_PRODUCTION
    project_id: !env CAPELLA_MAIN_PROJECT_ID_PRODUCTION
  stage:
    organization_id: !env CAPELLA_MAIN_ORGANIZATION_ID_STAGE
    project_id: !env CAPELLA_MAIN_PROJECT_ID_STAGE

services: 
  - kv 
  - n1ql
  - index
  - fts
  - cbas
  - eventing

clusters_local:
  development:
    main: standard_cluster_local_development
  test:
    main: standard_cluster_local_test

clusters_local_and_capella:
  production:
    main: standard_cluster_capella_production
  stage:
    main: standard_cluster_capella_stage
  development:
    main: standard_cluster_local_development
  test:
    main: standard_cluster_local_test

clusters_local_and_capella_aws_eu_central:
  production:
    main: standard_cluster_capella_aws_eu_central_production
  stage:
    main: standard_cluster_capella_aws_eu_central_stage
  development:
    main: standard_cluster_local_development
  test:
    main: standard_cluster_local_test

cluster_local_development:
  type: local
  module: couchbase
  change_client_id: _default
  spec: standard_cluster_spec_local
  bucket_spec_metadata: standard_bucket_spec_metadata_development
  connection: standard_connection_local_development
  credentials: standard_credentials_default

cluster_local_test:
  type: local
  module: couchbase
  change_client_id: _default
  spec: standard_cluster_spec_local_test
  bucket_spec_metadata: standard_bucket_spec_metadata_test
  connection: standard_connection_local_test
  credentials: standard_credentials_default

cluster_capella_production:
  type: capella
  capella_project_id: production 
  change_client_id: change
  cloud: standard_cloud
  spec: standard_cluster_spec_capella_production
  service_groups: standard_service_groups_production
  bucket_spec_metadata: standard_bucket_spec_metadata_production
  connection: standard_connection_capella_production
  credentials: standard_credentials_capella_production

cluster_capella_stage:
  type: capella
  capella_project_id: stage 
  change_client_id: change
  cloud: standard_cloud
  spec: standard_cluster_spec_capella_stage
  service_groups: standard_service_groups_stage
  bucket_spec_metadata: standard_bucket_spec_metadata_stage
  connection: standard_connection_capella_stage
  credentials: standard_credentials_capella_stage

cluster_capella_aws_eu_central_production:
  type: capella
  capella_project_id: production 
  change_client_id: change
  cloud: standard_cloud_aws_eu_central
  spec: standard_cluster_spec_capella_production
  service_groups: standard_service_groups_production
  bucket_spec_metadata: standard_bucket_spec_metadata_production
  connection: standard_connection_capella_aws_eu_central_production
  credentials: standard_credentials_capella_aws_eu_central_production

cluster_capella_aws_eu_central_central_stage:
  type: capella
  capella_project_id: stage 
  change_client_id: change
  cloud: standard_cloud_aws_eu_central
  spec: standard_cluster_spec_capella_stage
  service_groups: standard_service_groups_stage
  bucket_spec_metadata: standard_bucket_spec_metadata_stage
  connection: standard_connection_capella_aws_eu_central_stage
  credentials: standard_credentials_capella_aws_eu_central_stage

cloud:
  provider: !env COUCHBASE_CLOUD_PROVIDER
  region: !ENV COUCHBASE_CLOUD_REGION

cloud_aws_eu_central:
  provider: aws
  region: 'eu-central-1'
  
cluster_spec_capella_production:
  type: capella_multi_node
  size: small
  service_tier: developer_pro
  auto_failover: true
  auto_failover_timeout: 30

cluster_spec_capella_stage:
  type: capella_multi_node
  size: small 
  service_tier: developer_pro
  auto_failover: true
  auto_failover_timeout: 30

cluster_spec_local:
  type: server_single_node
  ram: 4096
  index_ram: 1024
  fts_ram: 512

cluster_spec_local_test:
  type: server_single_node
  ram: 4096
  index_ram: 1024
  fts_ram: 512

service_groups_production:
  main:
    services: ['kv', 'index', 'n1ql', 'fts']
    nodes: 3
    cpu: 16
    ram: 32
    disk: 
      storage: 50
      type: gp3
      iops: 3000

service_groups_stage:
  main:
    services: ['kv', 'index', 'n1ql', 'fts']
    nodes: 3
    cpu: 16
    ram: 32
    disk: 
      storage: 50
      type: gp3
      iops: 3000

bucket_spec_metadata_production:
  ram: 512
  replicas: 2
  durability: majority

bucket_spec_metadata_stage:
  ram: 512
  replicas: 2
  durability: majority

bucket_spec_metadata_development:
  ram: 256 
  replicas: 0
  durability: none

bucket_spec_metadata_test:
  ram: 256 
  replicas: 0
  durability: none

connection_capella_production:
  protocol: couchbases
  host: !env COUCHBASE_PRODUCTION_HOST
  port: 18091

connection_capella_stage:
  protocol: couchbases
  host: !env COUCHBASE_STAGE_HOST
  port: 18091

connection_local_development:
  protocol: couchbase
  host: couchbase
  port: 8091

connection_local_test:
  protocol: couchbase
  host: couchbase
  port: 8092

credentials_production:
  api:
    type: basic
    username: !env COUCHBASE_PRODUCTION_API_USERNAME
    password: !env COUCHBASE_PRODUCTION_API_PASSWORD
  change:
    type: basic
    username: !env COUCHBASE_PRODUCTION_CHANGE_USERNAME
    password: !env COUCHBASE_PRODUCTION_CHANGE_PASSWORD

credentials_stage:
  api:
    type: basic
    username: !env COUCHBASE_STAGE_API_USERNAME
    password: !env COUCHBASE_STAGE_API_PASSWORD
  change:
    type: basic
    username: !env COUCHBASE_STAGE_CHANGE_USERNAME
    password: !env COUCHBASE_STAGE_CHANGE_PASSWORD

credentials_default:
  _default: 
    type: basic
    username: admin
    password: password 
      
