local_and_cloud_eu:
  data_structures: standard_data_structure
  metadata: standard_metadata
  clusters: standard_clusters_local_and_cloud_eu

data_structure:
  main:
    type: cluster

metadata:
  topics_prefix: metadata

clusters_local_and_cloud_eu:
  production: standard_cloud_cluster_eu_production
  stage: standard_cloud_cluster_eu_stage
  development: standard_local_single_node_cluster_development
  test: standard_local_single_node_cluster_test
  
cloud_cluster_eu_production:
  type: cloud
  change_client_id: change
  cloud: standard_cloud_eu
  metadata_topics_specs: standard_metadata_topics_specs_production

cloud_cluster_eu_stage:
  type: cloud
  change_client_id: change
  cloud: standard_cloud_eu
  metadata_topics_specs: standard_metadata_topics_specs_stage

local_single_node_cluster_development:
  type: polytope
  module: redpanda
  change_client_id: _default
  metadata_topics_specs: standard_metadata_topics_specs_development

local_single_node_cluster_test:
  type: polytope
  module: redpanda
  change_client_id: _default
  metadata_topics_specs: standard_metadata_topics_specs_test

cloud_eu:
  type: aws
  region: 'eu-central-1'

metadata_topics_specs_production:
  partitions: 3
  replication_factor: 3

metadata_topics_specs_stage:
  partitions: 2
  replication_factor: 2

metadata_topics_specs_development:
  partitions: 1
  replication_factor: 1

metadata_topics_specs_test:
  partitions: 1
  replication_factor: 1

local_and_cloud:
  production: standard_production_cloud
  stage: standard_stage_cloud
  development: standard_development_local
  test: standard_test_local

production_cloud:
  connection: standard_production_connection_cloud
  credentials: standard_production_credentials

stage_cloud:
  connection: standard_stage_connection_cloud
  credentials: standard_stage_credentials

development_local:
  connection: standard_development_connection_local
  credentials: null

test_local:
  connection: standard_test_connection_local
  credentials: null

production_connection_cloud:
  bootstrap_servers:
    - host: !env REDPANDA_PRODUCTION_HOST
      port: !env REDPANDA_PRODUCTION_PORT
  security_protocol: SSL
  ssl_ca_location: !env REDPANDA_PRODUCTION_SSL_CA_LOCATION
  ssl_certificate_location: !env REDPANDA_PRODUCTION_SSL_CERTIFICATE_LOCATION
  ssl_key_location: !env REDPANDA_PRODUCTION_SSL_CERT

stage_connection_cloud:
  bootstrap_servers:
    - host: !env REDPANDA_STAGE_HOST
      port: !env REDPANDA_STAGE_PORT
  security_protocol: SSL
  ssl_ca_location: !env REDPANDA_STAGE_SSL_CA_LOCATION
  ssl_certificate_location: !env REDPANDA_STAGE_SSL_CERTIFICATE_LOCATION
  ssl_key_location: !env REDPANDA_STAGE_SSL_CERT

development_connection_local:
  bootstrap_servers:
    - host: !env REDPANDA_DEVELOPMENT_HOST
      port: !env REDPANDA_DEVELOPMENT_PORT 

test_connection_local:
  bootstrap_servers:
    - host: !env REDPANDA_TEST_HOST
      port: !env REDPANDA_TEST_PORT

production_credentials:
  api:
    security_protocol: SASL_PLAINTEXT
    sasl_mechanism: SCRAM-SHA-256
    sasl_plain_username: !env REDPANDA_PRODUCTION_API_USERNAME
    sasl_plain_password: !env REDPANDA_PRODUCTION_API_PASSWORD
  change:
    security_protocol: SASL_PLAINTEXT
    sasl_mechanism: SCRAM-SHA-256
    sasl_plain_username: !env REDPANDA_PRODUCTION_CHANGE_USERNAME
    sasl_plain_password: !env REDPANDA_PRODUCTION_CHANGE_PASSWORD

stage_credentials:
  api:
    security_protocol: SASL_PLAINTEXT
    sasl_mechanism: SCRAM-SHA-256
    sasl_plain_username: !env REDPANDA_STAGE_API_USERNAME
    sasl_plain_password: !env REDPANDA_STAGE_API_PASSWORD
  change:
    security_protocol: SASL_PLAINTEXT
    sasl_mechanism: SCRAM-SHA-256
    sasl_plain_username: !env REDPANDA_STAGE_CHANGE_USERNAME
    sasl_plain_password: !env REDPANDA_STAGE_CHANGE_PASSWORD

