# Configurations for which data stores should be managed for each 
# environment. The data stores are configured in the datastores.yml
# file.
#
# Structure:
#
# <environment>: 
#   - <data store id>
#

production: 
  couchbase:
    - production
  redpanda: production

stage: 
  couchbase: stage
  redpanda: stage

development:
  couchbase: development
  redpanda: development

test: 
  couchbase: test
  redpanda: test
