_format_version: '2.1'
_transform: true

# NOTE: for health checks
routes:
  - name: root-route
    paths: [/]
    methods: [GET]
    service: null

plugins:
  - name: request-termination
    route: root-route
    config:
      status_code: 200

services:
- name: oauth-agent-web-app
  url: http://oauth-agent-web-app:3001/oauth-agent
  routes:
  - name: oauth-agent-web-app-route
    paths:
    - /oauth-agent-web-app

  plugins:
  - name: cors
    config:
      origins:
      - $CILLERS_WEB_APP_URL
      methods:
      - GET
      - POST
      - OPTIONS
      headers:
      - Accept
      - Authorization
      - Content-Type
      - x-curity-csrf
      exposed_headers:
      - Authorization
      credentials: true
      preflight_continue: false

- name: oauth-agent-api-client-graphql
  url: http://oauth-agent-api-client-graphql:3002/oauth-agent
  routes:
  - name: oauth-agent-api-client-graphql-route
    paths:
    - /oauth-agent-api-client-graphql

  plugins:
  - name: cors
    config:
      origins:
      - $CILLERS_API_CLIENT_GRAPHQL_URL
      methods:
      - GET
      - POST
      - OPTIONS
      headers:
      - Accept
      - Authorization
      - Content-Type
      - x-curity-csrf
      exposed_headers:
      - Authorization
      credentials: true
      preflight_continue: false
        
- name: oauth-agent-api-client-rest
  url: http://oauth-agent-api-client-rest:3003/oauth-agent
  routes:
  - name: oauth-agent-api-client-rest-route
    paths:
    - /oauth-agent-api-client-rest

  plugins:
  - name: cors
    config:
      origins:
      - $CILLERS_API_CLIENT_REST_URL
      methods:
      - GET
      - POST
      - OPTIONS
      headers:
      - Accept
      - Authorization
      - Content-Type
      - x-curity-csrf
      exposed_headers:
      - Authorization
      credentials: true
      preflight_continue: false
    
- name: api
  url: http://api:4000
  routes:
  - name: api-route
    strip_path: false
    paths:
    - /api

  plugins:
    - name: oauth-proxy
      config:
        cookie_name_prefix: curity
        encryption_key: fda91643fce9af565bdc34cd965b48da75d1f5bd8846bf0910dd6d7b10f06dfe
        trusted_web_origins:
        - $CILLERS_WEB_APP_URL
        - $CILLERS_API_CLIENT_GRAPHQL_URL
        - $CILLERS_API_CLIENT_REST_URL
        cors_enabled: true 
        allow_tokens: true

    - name: phantom-token
      config:
        introspection_endpoint: http://curity:8443/oauth/v2/oauth-introspect
        client_id: kong-introspection 
        client_secret: Password1
        token_cache_seconds: 900
        verify_ssl: false

    - name: cors
      config:
        origins:
        - $CILLERS_WEB_APP_URL
        - $CILLERS_API_CLIENT_GRAPHQL_URL
        - $CILLERS_API_CLIENT_REST_URL
        methods:
        - GET
        - POST
        - OPTIONS
        headers:
        - Accept
        - Authorization
        - Content-Type
        - x-curity-csrf
        exposed_headers:
        - Authorization
        credentials: true
        preflight_continue: false 

